name:                gl-wrapper-gen
version:             0.1.0.0
github:              "githubuser/gl-wrapper-gen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gl-wrapper-gen#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  gl-wrapper-gen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    dependencies:
    - containers
    - directory
    - lens
    - shakespeare
    - tagsoup
    - text
    - xml-conduit
    - xml-lens
